FROM python:3.12-slim

WORKDIR /app

ENV PYTHONPATH=/app/src
ENV TZ=Europe/Moscow
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--app-dir", "src"]